### PR TITLE
feat(gwm): create OIDC client per solution

### PR DESCRIPTION
**Pull request by obdulia-losantos**
Create a specific client per solution (this allows to choose a different login theme or disable a solution without disabling the whole realm).

### CODE REVIEW

**Review by shawnsarwar — APPROVED** [review]
@obdulia-losantos How this work in practice? The OIDC plugin is associate with a single client per route if IIRC. So if you're logged into PF Planner, do you need to login again to view aether-kernel? Just curious.

**Comment by obdulia-losantos** [comment]
:thinking: let me try with `aether-bootstrap`...

**Comment by obdulia-losantos** [comment]
I tested this PR: https://github.com/eHealthAfrica/aether-bootstrap/pull/156

I entered via gather (using `kong-gather` client) and after that went to kernel (using `kong-aether` client), I didn't re-log in. Keycloak detects that it's the same browser/window and joins both accesses in the same session.

image

**Review by Timtech4u — APPROVED** [review]
looks good to me

**Pull request merged**
